apiVersion: angi.ryan.evans.com/v1
kind: PodInfo
metadata:
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/instance: podinfo-sample
    app.kubernetes.io/part-of: angi-takehome
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: angi-takehome
  name: podinfo-sample
spec:
  # TODO(user): Add fields here
