apiVersion: angi.ryan.evans.com/v1
kind: PodInfo
metadata:
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/instance: podinfo-sample
    app.kubernetes.io/part-of: angi-takehome
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: angi-takehome
  name: podinfo-sample
spec:
  replicaCount: 3
  resources:
    memoryLimit: 64Mi
    cpuRequest: 100m
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: latest
  ui:
    color: "#34577c"
    message: "ryan is awesome 34324"
  redis:
    enabled: true
